### ISSUE TITLE
TASK 2251 | STAGE 5 (a wrong way to pass it)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#175]
I can pass all checks by
```css
.section div {
  padding: 0px 150px;
}
.section-description {
  flex-grow: 1;
}
.section-image {
  display: flex;
  justify-content: center;
  flex-grow: 1;
}
```
It looks like this
![image](https://user-images.githubusercontent.com/18144023/117535209-5e620180-affd-11eb-9a63-712278172dc9.png)
I've done it by following the requirements
`Add the 'section-description' class to the first of these two blocks, and the 'section-image' class to the second, the blocks should have a horizontal padding of 150px.`

But as I got later you wanted from me that
```css
/* .section div {
  padding: 0px 150px;
} */
.section-description {
  padding: 0px 150px;
  flex-grow: 1;
}
.section-image {
  padding: 0px 150px;
  display: flex;
  justify-content: center;
  flex-grow: 1;
}
```
Now It looks better.
![image](https://user-images.githubusercontent.com/18144023/117535282-bc8ee480-affd-11eb-938e-4aa40dcea71d.png)

P.S. There're some additional styles from next stages. Just ignore them.
